language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update $COMPOSER_OPTS

script:
  - if [ "$TRAVIS_PHP_VERSION" == 7 ]; then vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" != 7 ]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi

