site_name: Redbox-cli
site_url: "https://johnnymast.github.io/redbox-cli"
site_description: 'This is a command line parser'
repo_name: 'johnnymast/redbox-cli'
repo_url: 'https://github.com/johnnymast/redbox-cli/tree/1.5'
theme:
  name: material
docs_dir: docs/
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - pymdownx.superfences
  - pymdownx.snippets
  - def_list
  - toc:
      permalink: true
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Arguments:
      - Introduction: arguments/introduction.md
      - Operations: arguments/operations.md
  - About:
    - Author: author.md
    - License: license.md
