name: Code Coverage

on:
  push:
    branches:
      - 1.5

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP Dependencies
        run: "composer install --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist"

      - name: Execute PHPUnit
        run: XDEBUG_MODE=coverage ./vendor/bin/pest --coverage --min=90

      - name: Updating branch.json
        run: php update_branch_json.php ${GITHUB_REF##*/}

      - name: Updating coverage.json
        run: php update_code_coverage.php

      - name: Commit coverage.json to Repo
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Johnny Mast
          author_email: mastjohnny@gmail.com
          message: "Committing code coverage image"
          add: "coverage.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit branch.json to Repo
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Johnny Mast
          author_email: mastjohnny@gmail.com
          message: "Committing code coverage image"
          add: "branch.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Updating README.md
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Johnny Mast
          author_email: mastjohnny@gmail.com
          message: "Updating README.md"
          add: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}